### ISSUE TITLE
About dataset and model （VRAM）

### ISSUE THREAD

**Issue by jun0wanan** [THUNLP-MT/StreamingBench#2]
Hello,

 thank you for your excellent work. I would like to ask, what is the maximum number of frames your videos can achieve? Some models may run out of GPU memory when testing a single example due to incompatibility with online videos that are too long. How do you handle this? Do you use frame sampling or other methods?

Looking forward to your reply, thank you!

**Comment by mjuicem** [comment]
Hello Jun0wanan,

Thank you for your thoughtful question and for reaching out!

Regarding your inquiry, the typical frame rate of the videos we work with is 30fps, although some videos may have frame rates of 24fps or 25fps. For offline video MLLMs, such as LLaVA-OneVision and Qwen2-VL, we follow the official frame sampling strategy as recommended in their official settings. For online video MLLMs like Flash-VStream and VideoLLM-Online, we also stick to the official settings without applying any additional frame sampling strategies.

So far, we have not encountered any issues with GPU memory running out. If you are working with offline video MLLMs, you could try reducing the frame sampling count to help manage memory usage more efficiently. If you're dealing with online video MLLMs and encountering GPU out-of-memory issues, you might want to try processing versions that only retain the first 60 seconds of context for the query. This can help alleviate memory constraints.

I hope this answers your question! If you have any more questions or need further clarification, please feel free to reach out.

Best regards !

**Comment by jun0wanan** [comment]
> Hello Jun0wanan,
> 
> Thank you for your thoughtful question and for reaching out!
> 
> Regarding your inquiry, the typical frame rate of the videos in our benchmark is 30fps, although some videos may have frame rates of 24fps or 25fps. For offline video MLLMs, we follow the official frame sampling strategy as recommended in their official settings, such as 32 frames for MiniCPM-V 2.6. For online video MLLMs like Flash-VStream and VideoLLM-Online, we also stick to the official settings without applying any additional frame sampling strategies.
> 
> So far, we have not encountered any issues with GPU memory running out. If you are working with offline video MLLMs, you could try reducing the frame sampling count to help manage memory usage more efficiently. If you're dealing with online video MLLMs and encountering GPU out-of-memory issues, you might want to try processing versions that only retain the first 60 seconds of context for the query. This can help alleviate memory constraints.
> 
> I hope this answers your question! If you have any more questions or need further clarification, please feel free to reach out.
> 
> Best regards !

Hello, thank you for your reply,

May I ask how many frames you specifically sampled for each video in offline models like qwen2vl and llava-ov?
For online models like flash, I believe its memory mechanism inputs 1 frame per second. Is that how you tested it?
Is this part included in the current code?

Thank you for your prompt response!~

**Comment by mjuicem** [comment]
Hello jun0wanan, thank you for your questions!

The number of samples for each offline video MLLM can be referenced in the image provided. Regarding Flash-VStream, our implementation also follows a 1 fps strategy (retaining the first frame of each second). You can find the corresponding code path in `StreamingBench/src/model/FlashVstream.py`.

Thanks again for reaching out!

Best regards !
<img width="1352" alt="截屏2024-11-15 22 39 48" src="https://github.com/user-attachments/assets/df173976-9256-4545-a7b7-67cd26a356df">

**Comment by jun0wanan** [comment]
> Hello jun0wanan, thank you for your questions!
> 
> The number of samples for each offline video MLLM can be referenced in the image provided. Regarding Flash-VStream, our implementation also follows a 1 fps strategy (retaining the first frame of each second). You can find the corresponding code in `StreamingBench/src/model/FlashVstream.py`.
> 
> Thanks again for reaching out!
> 
> Best regards ! <img alt="截屏2024-11-15 22 39 48" width="1352" src="https://private-user-images.githubusercontent.com/114148730/386647116-df173976-9256-4545-a7b7-67cd26a356df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2ODI4MjYsIm5iZiI6MTczMTY4MjUyNiwicGF0aCI6Ii8xMTQxNDg3MzAvMzg2NjQ3MTE2LWRmMTczOTc2LTkyNTYtNDU0NS1hN2I3LTY3Y2QyNmEzNTZkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQxNDU1MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05M2FlYzRjYTEyNTFjZDU1ZGQ5MzU4YTFiZWJlZTRiNGY1OTZmNGU4ZTUyNWMzOWQ2YTg0MjBiODgzNjY5YjE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1Vpv-2lXZm_qrrFrBtUwpPHIJjaa46G03mEnIExTdec">

Thanks！:)

**Comment by jun0wanan** [comment]
hi ,
`save the results to the specified output file.` , but how to get the score :) @mjuicem , Thank you ~

**Comment by mjuicem** [comment]
Hello jun0wanan,

We apologize for previously overlooking the inclusion of instructions for calculating the metrics. We have now updated the README with the necessary details.

Specifically, once you save the results to the specified output file, you can calculate the metrics using the following command: `bash stats.sh`

Thank you for bringing this to our attention. Please let us know if you have any further questions.

**Comment by jun0wanan** [comment]
> Thanks！:)

Thanks！:) Best wishes~

**Comment by jun0wanan** [comment]
> Hello jun0wanan,
> 
> We apologize for previously overlooking the inclusion of instructions for calculating the metrics. We have now updated the README with the necessary details.
> 
> Specifically, once you save the results to the specified output file, you can calculate the metrics using the following command: `bash stats.sh`
> 
> Thank you for bringing this to our attention. Please let us know if you have any further questions.

Thanks！:) Best wishes~

**Comment by jun0wanan** [comment]
hi, 
when I run eval.sh   - I have a bug on 
`
clip.write_videofile("output_video.mp4")
`
-
`
 '-r', '%.02f' % fps,
          ~~~~~~~~^~~~~

TypeError: must be real number, not NoneType
`
maybe I should set the fps like:
`clip.write_videofile("output_video.mp4", fps=30)`
?

**Comment by jun0wanan** [comment]
> Hello jun0wanan,
> 
> We apologize for previously overlooking the inclusion of instructions for calculating the metrics. We have now updated the README with the necessary details.
> 
> Specifically, once you save the results to the specified output file, you can calculate the metrics using the following command: `bash stats.sh`
> 
> Thank you for bringing this to our attention. Please let us know if you have any further questions.

hi , I find the qa_real.json have some question about the query's timestamp 
eg: sample_103_real  
`
{
        "time": "[0:04:00 - 0:05:00]",
        "questions": [
            {
                "task_type": "Counting",
                "question": "How many times in total have movie clips been inserted during this person's explanation so far?",
                "time_stamp": "00:04:00",  # the whole video time is 3:59
                "answer": "D",
                "options": [
                    "A. 2.",
                    "B. 8.",
                    "C. 3.",
                    "D. 0."
                ],
                "required_ability": "episodic memory"
            }
        ],
        "video_categories": "introduction_to_film",
        "video_path": "./videos/sample_103_real.mp4"
    },
`

I find your csv is correct. 
`
Real-Time Visual Understanding_sample_103_1,Counting,How many times in total have movie clips been inserted during this person's explanation so far?,00:00:16,D,"['A. 2.', 'B. 3.', 'C. 4.', 'D. 0.']",multiple,Concurrent
`

**Comment by mjuicem** [comment]
Hi jun0wanan,

Thank you for your question! Regarding the `frame_num` in the file name `sample_348_real_0_31.mp4`, the code extracts it by splitting the file path using `'/'` and `'_'`. Specifically, the second-to-last element after splitting by `'_'` is `31`. So, in this case, `frame_num = 31`.  

As for your second question about changing the current assessment method to support multi-GPU, it’s an excellent suggestion! We are planning to update it shortly and will keep you informed of the progress. Please feel free to share any specific needs or suggestions you might have for this enhancement.  

We sincerely apologize for the error in `qa_real.json`, and greatly appreciate your attention to detail in identifying it. The incorrect question should be replaced with the following:
 `Real-Time Visual Understanding_sample_103_5 | Counting | How many times in total have movie clips been inserted during this person's explanation so far? | 00:03:26 | D | ['A. 3.', 'B. 4.', 'C. 6.', 'D. 0.'] | multiple | Concurrent`


Looking forward to your feedback!

Best regards!

**Comment by jun0wanan** [comment]
> Hi jun0wanan,
> 
> Thank you for your question! Regarding the `frame_num` in the file name `sample_348_real_0_31.mp4`, the code extracts it by splitting the file path using `'/'` and `'_'`. Specifically, the second-to-last element after splitting by `'_'` is `31`. So, in this case, `frame_num = 31`.
> 
> As for your second question about changing the current assessment method to support multi-GPU, it’s an excellent suggestion! We are planning to update it shortly and will keep you informed of the progress. Please feel free to share any specific needs or suggestions you might have for this enhancement.
> 
> We sincerely apologize for the error in `qa_real.json`, and greatly appreciate your attention to detail in identifying it. The incorrect question should be replaced with the following: `Real-Time Visual Understanding_sample_103_5 | Counting | How many times in total have movie clips been inserted during this person's explanation so far? | 00:03:26 | D | ['A. 3.', 'B. 4.', 'C. 6.', 'D. 0.'] | multiple | Concurrent`
> 
> Looking forward to your feedback!
> 
> Best regards!

Thank you for your response. I discovered that besides the example I mentioned, there are some other cases that also exceed the limit. Currently, I'm testing by removing all these problematic cases. I hope you could help check again, as it seems there are more examples beyond the one mentioned above. I'm not very familiar with this dataset, so I'm concerned it might be my own issue  hh...
