### ISSUE TITLE
the average video length

### ISSUE THREAD

**Issue by patrick-tssn** [THUNLP-MT/StreamingBench#4]
Hi, Thank you for your excellent work! Could you kindly provide the average length of all 900 videos? I’d greatly appreciate it. Thanks a lot!

**Comment by Fzacker** [comment]
Hello patrick-tssn, thank you for your questions!

The average length of 900 videos is 243.139s(4min 3s). And the distribution of video length is as follows:
![dist](https://github.com/user-attachments/assets/a2104b1e-a24d-42e1-9b4f-bc0399415c52)

I hope this answers your question!

Best regards !

**Comment by patrick-tssn** [comment]
Thank you for your answer!
